export const adminActionErrorMessages: Record<string, string> = {
  category_missing_fields: "카테고리 키와 라벨을 입력해 주세요.",
  category_invalid_key: "카테고리 키 형식을 확인해 주세요.",
  category_invalid_color: "카테고리 색상은 #RRGGBB 형식이어야 합니다.",
  category_invalid_request: "카테고리 입력값을 확인해 주세요.",
  category_delete_deferred:
    "데이터 보호를 위해 카테고리 삭제는 현재 잠겨 있습니다. 이름과 설명은 수정할 수 있습니다.",
  company_missing_name: "파트너사명을 입력해 주세요.",
  company_invalid_email: "담당자 이메일 형식이 올바르지 않습니다.",
  company_invalid_request: "파트너사 입력값을 확인해 주세요.",
  cycle_missing_fields: "기준 기수, 기준 연도, 기준 월을 모두 입력해 주세요.",
  cycle_invalid_number: "기준값은 허용된 범위의 숫자로 입력해 주세요.",
  cycle_invalid_request: "기수 기준 입력값을 확인해 주세요.",
  cohort_theme_missing_fields: "기수와 카드 색상을 모두 입력해 주세요.",
  cohort_theme_invalid_year: "카드 색상 기수는 1~99 사이의 숫자로 입력해 주세요.",
  cohort_theme_invalid_color: "카드 색상은 #RRGGBB 형식으로 입력해 주세요.",
  cohort_theme_invalid_request: "기수별 카드 색상 입력값을 확인해 주세요.",
  member_missing_id: "대상을 찾을 수 없습니다.",
  member_invalid_year: "기수는 0~99 사이의 숫자로 입력해 주세요.",
  member_invalid_request: "회원 입력값을 확인해 주세요.",
  partner_account_missing_id: "대상을 찾을 수 없습니다.",
  partner_account_invalid_email: "담당자 이메일 형식이 올바르지 않습니다.",
  partner_account_invalid_request: "파트너사 계정 입력값을 확인해 주세요.",
  partner_account_exists: "이미 존재하는 로그인 아이디입니다.",
  partner_account_company_missing: "연결할 계정과 회사를 찾을 수 없습니다.",
  partner_account_company_invalid_request: "연결 상태 입력값을 확인해 주세요.",
  regional_admin_scope_denied: "배정된 지역의 제휴처 또는 파트너사만 관리할 수 있습니다.",
  admin_global_scope_required: "전역 관리자만 수행할 수 있는 작업입니다.",
  partner_company_plan_invalid_request: "플랜 입력값을 확인해 주세요.",
  partner_company_plan_missing_request: "플랜 요청을 찾을 수 없습니다.",
  partner_company_plan_pending_exists: "이미 처리 대기 중인 업그레이드 요청이 있습니다.",
  partner_company_plan_processed: "이미 처리된 업그레이드 요청입니다.",
  partner_company_plan_payment_unconfirmed: "입금 확인 후 플랜을 승인할 수 있습니다.",
  review_invalid_request: "리뷰 입력값을 확인해 주세요.",
  review_not_found: "대상을 찾을 수 없습니다.",
};
