export const adminActionErrorMessages: Record<string, string> = {
  category_missing_fields: "카테고리 키와 라벨을 입력해 주세요.",
  category_invalid_key: "카테고리 키 형식을 확인해 주세요.",
  category_invalid_color: "카테고리 색상은 #RRGGBB 형식이어야 합니다.",
  category_invalid_request: "카테고리 입력값을 확인해 주세요.",
  company_missing_name: "협력사명을 입력해 주세요.",
  company_invalid_email: "담당자 이메일 형식이 올바르지 않습니다.",
  company_invalid_request: "협력사 입력값을 확인해 주세요.",
  cycle_missing_fields: "기준 기수, 기준 연도, 기준 월을 모두 입력해 주세요.",
  cycle_invalid_number: "기준값은 허용된 범위의 숫자로 입력해 주세요.",
  cycle_invalid_request: "기수 기준 입력값을 확인해 주세요.",
  member_missing_id: "대상을 찾을 수 없습니다.",
  member_invalid_year: "기수는 0~99 사이의 숫자로 입력해 주세요.",
  member_invalid_request: "회원 입력값을 확인해 주세요.",
  partner_account_missing_id: "대상을 찾을 수 없습니다.",
  partner_account_invalid_email: "담당자 이메일 형식이 올바르지 않습니다.",
  partner_account_invalid_request: "업체 계정 입력값을 확인해 주세요.",
  partner_account_company_missing: "연결할 계정과 회사를 찾을 수 없습니다.",
  partner_account_company_invalid_request: "연결 상태 입력값을 확인해 주세요.",
};
