import type { ProductEventName, AdminAuditAction, AuthSecurityEventName } from "./event-catalog";

export const PRODUCT_EVENT_LABELS = {
  page_view: "페이지 조회",
  partner_detail_view: "파트너 상세 조회",
  partner_card_click: "파트너 카드 클릭",
  category_filter_change: "카테고리 필터 변경",
  directory_view_change: "목록 보기 변경",
  search_execute: "검색 실행",
  sort_change: "정렬 변경",
  partner_map_click: "지도 클릭",
  reservation_click: "예약 클릭",
  inquiry_click: "문의 클릭",
  partner_benefit_use_open: "혜택 사용 화면 열기",
  partner_benefit_use_select: "혜택 선택",
  partner_benefit_use_confirm: "혜택 사용 확인",
  partner_benefit_use_pin_attempt: "혜택 사용 인증 시도",
  partner_benefit_use_success: "혜택 사용 인증 성공",
  partner_benefit_use_failure: "혜택 사용 인증 실패",
  partner_benefit_use: "혜택 사용",
  share_link_copy: "공유 링크 복사",
  push_settings_view: "알림 설정 조회",
  push_subscribe: "푸시 구독",
  push_unsubscribe_device: "현재 기기 알림 해제",
  push_unsubscribe_all: "모든 기기 알림 해제",
  push_preference_change: "푸시 설정 변경",
  suggest_submit: "제휴처 제안 제출",
  partner_registration_submit: "파트너 등록 신청",
  partner_registration_xlsx_submit: "파트너 등록 엑셀 신청",
  partner_portal_brand_registration_submit: "포털 제휴처 등록 신청",
  pwa_install_click: "PWA 설치 클릭",
  certification_view: "내 인증 조회",
  certification_qr_open: "교육생 QR 열기",
  certification_qr_verify: "교육생 QR 검증",
  wallet_pass_issue: "지갑 패스 발급",
  wallet_pass_download: "지갑 패스 내려받기",
  wallet_pass_verify: "지갑 패스 검증",
  wallet_pass_revoke: "지갑 패스 폐기",
  wallet_pass_device_register: "지갑 기기 등록",
  wallet_pass_device_unregister: "지갑 기기 해제",
  wallet_pass_sync: "지갑 패스 동기화",
  partner_review_create: "리뷰 등록",
  partner_review_update: "리뷰 수정",
  partner_review_delete: "리뷰 삭제",
  partner_review_recommend: "리뷰 추천",
  partner_review_disrecommend: "리뷰 비추천",
  home_banner_click: "홈 배너 클릭",
  coupon_view: "쿠폰 조회",
  coupon_copy: "쿠폰 코드 복사",
  coupon_redeem: "쿠폰 사용",
  ad_push_send: "광고 알림 발송",
  admin_web_vital: "관리자 웹 성능 측정",
  admin_route_timing: "관리자 화면 이동 측정",
  admin_prefetch: "관리자 화면 미리 읽기",
  admin_task_start: "관리자 작업 시작",
  admin_task_complete: "관리자 작업 완료",
  admin_task_recovery: "관리자 작업 오류 복구",
} as const satisfies Readonly<Record<ProductEventName, string>>;

export const ADMIN_AUDIT_LABELS = {
  login: "관리자 로그인",
  logout: "관리자 로그아웃",
  category_create: "카테고리 생성",
  category_update: "카테고리 수정",
  category_delete: "카테고리 삭제",
  partner_company_create: "파트너사 생성",
  partner_company_update: "파트너사 수정",
  partner_company_delete: "파트너사 삭제",
  partner_create: "제휴처 생성",
  partner_update: "제휴처 수정",
  partner_preview_link_create: "제휴처 미리보기 링크 생성",
  partner_preview_link_remove: "제휴처 미리보기 링크 제거",
  partner_change_request_approve: "제휴처 변경 요청 승인",
  partner_change_request_reject: "제휴처 변경 요청 거절",
  member_update: "회원 수정",
  member_directory_sync: "회원 디렉토리 동기화",
  member_sync: "회원 정보 동기화",
  member_mattermost_login_disable_generation: "기수 Mattermost 로그인 중단",
  member_email_login_transition: "회원 이메일 로그인 전환",
  member_manual_add: "회원 수동 추가",
  member_manual_setup_link_reissue: "수동 회원 초기 설정 링크 재발급",
  member_password_reset_link_generate: "회원 비밀번호 재발급 링크 생성",
  member_password_reset_link_send: "회원 비밀번호 재발급 이메일 발송",
  member_direct_create: "회원 직접 생성",
  member_delete: "회원 삭제",
  cycle_settings_update: "기수 기준 수정",
  cycle_settings_early_start: "기수 조기 시작",
  cycle_settings_restore: "기수 기준 복구",
  cohort_card_theme_upsert: "기수 인증 카드 테마 저장",
  cohort_card_theme_delete: "기수 인증 카드 테마 삭제",
  mattermost_sender_candidate_save: "Mattermost 발송자 후보 저장",
  mattermost_sender_test: "Mattermost 발송자 테스트",
  mattermost_sender_activate: "Mattermost 발송자 활성화",
  mattermost_sender_disable: "Mattermost 발송자 비활성화",
  push_send: "푸시 발송",
  push_log_delete: "푸시 로그 삭제",
  partner_account_update: "파트너사 포털 계정 수정",
  partner_account_create: "파트너사 포털 계정 추가",
  partner_account_company_update: "파트너사 포털 연결 수정",
  partner_account_initial_setup_link_generate: "파트너사 포털 초기설정 URL 생성",
  partner_account_initial_setup_link_send: "파트너사 포털 초기설정 URL 전송",
  partner_review_hide: "리뷰 숨김",
  partner_review_restore: "리뷰 복원",
  partner_review_update: "리뷰 수정",
  partner_review_delete: "리뷰 삭제",
  partner_portal_immediate_update: "파트너사 포털 즉시 수정",
  partner_portal_change_request_submit: "파트너사 포털 변경 요청 제출",
  partner_portal_change_request_cancel: "파트너사 포털 변경 요청 취소",
  partner_portal_review_hide: "파트너사 포털 리뷰 숨김",
  partner_portal_review_restore: "파트너사 포털 리뷰 복구",
  partner_benefit_usage_create: "혜택 사용 기록 생성",
  partner_benefit_usage_update: "혜택 사용 기록 수정",
  partner_benefit_usage_delete: "혜택 사용 기록 삭제",
  promotion_event_create: "프로모션 이벤트 생성",
  promotion_event_update: "프로모션 이벤트 수정",
  promotion_event_delete: "프로모션 이벤트 삭제",
  promotion_slide_create: "프로모션 슬라이드 생성",
  promotion_slide_update: "프로모션 슬라이드 수정",
  promotion_slide_delete: "프로모션 슬라이드 삭제",
  promotion_slide_bulk_update: "프로모션 슬라이드 일괄 수정",
  event_reward_draw_preview: "이벤트 추첨 테스트",
  event_reward_draw_create: "이벤트 추첨 확정",
  showcase_event_settings_update: "쇼케이스 설정 수정",
  showcase_project_create: "쇼케이스 출품 등록",
  showcase_project_update: "쇼케이스 출품 수정",
  showcase_project_delete: "쇼케이스 출품 삭제",
  showcase_project_review: "쇼케이스 출품 검토",
  showcase_feedback_visibility_update: "쇼케이스 피드백 공개 설정",
  showcase_public_draw: "쇼케이스 공개 추첨",
  showcase_candidate_exclusion_update: "쇼케이스 추첨 후보 제외 설정",
  showcase_winner_update: "쇼케이스 당첨자 수정",
  showcase_event_settle: "쇼케이스 정산 종료",
  event_reward_winner_notification_test_send: "이벤트 당첨 안내 테스트 발송",
  event_reward_winner_notification_send: "이벤트 당첨 안내 발송",
  ad_campaign_create: "광고 캠페인 생성",
  ad_campaign_status_update: "광고 캠페인 상태 변경",
  ad_coupon_create: "쿠폰 생성",
  ad_coupon_update: "쿠폰 수정",
  ad_coupon_duplicate: "쿠폰 복제",
  ad_coupon_delete: "쿠폰 삭제",
  partner_brand_plan_update: "파트너 제휴처 플랜 변경",
  partner_company_plan_update: "제휴처 플랜 변경",
  partner_plan_bank_transfer_confirmed: "파트너 입금 확인",
  partner_plan_upgrade_approved: "제휴처 플랜 업그레이드 승인",
  partner_plan_upgrade_rejected: "제휴처 플랜 업그레이드 반려",
  admin_account_create: "관리자 계정 생성",
  admin_account_setup_link_issue: "관리자 초기 설정 링크 발급",
  admin_account_status_update: "관리자 계정 상태 변경",
  admin_account_permissions_update: "관리자 권한 변경",
  admin_account_template_apply: "관리자 권한 템플릿 적용",
  graduate_verification_review_start: "수료생 인증 검토 시작",
  graduate_verification_approve: "수료생 인증 승인",
  graduate_verification_setup_email_resend: "수료생 초기 설정 이메일 재발송",
  graduate_verification_reject: "수료생 인증 반려",
  graduate_verification_resubmission_request: "수료생 인증 보완 요청",
  member_profile_photo_approve: "회원 프로필 사진 승인",
  member_profile_photo_reject: "회원 프로필 사진 반려",
  member_profile_photo_active_reject: "회원 승인 사진 철회",
  member_profile_photo_replace: "회원 프로필 사진 교체",
  graduate_certificate_view: "수료증 조회",
  graduate_profile_photo_view: "수료생 프로필 사진 조회",
  member_profile_photo_view: "회원 프로필 사진 조회",
  member_signup_approval_approve: "회원 가입 신청 승인",
  member_signup_approval_reject: "회원 가입 신청 반려",
  notification_template_update: "알림 템플릿 수정",
  notification_template_reset: "알림 템플릿 초기화",
  notification_template_test_send: "알림 템플릿 테스트 발송",
  admin_log_export_requested: "관리 로그 내보내기 요청",
  showcase_personal_data_purge: "쇼케이스 개인정보 파기",
  member_detail_view: "회원 상세 조회",
  log_retention_purge: "보존 기간 만료 로그 파기",
} as const satisfies Readonly<Record<AdminAuditAction, string>>;

export const AUTH_SECURITY_LABELS = {
  member_login: "회원 로그인",
  member_logout: "회원 로그아웃",
  member_signup_complete: "회원가입 완료",
  member_signup_approval_request: "회원 가입 승인 요청",
  member_mattermost_code: "Mattermost DM 코드 인증",
  member_email_recovery: "회원 이메일 계정 복구",
  member_email_verification: "회원 이메일 인증",
  member_policy_consent: "약관 동의",
  member_password_reset_complete: "비밀번호 재설정 완료",
  member_password_reset: "비밀번호 재설정",
  member_password_change: "비밀번호 변경",
  member_delete: "회원 탈퇴",
  graduate_email_verification: "수료생 이메일 인증",
  graduate_verification_submit: "수료생 인증 신청",
  graduate_password_setup: "수료생 비밀번호 설정",
  graduate_password_reset: "수료생 비밀번호 재설정",
  admin_login: "관리자 로그인",
  admin_access: "관리자 접근 제어",
  partner_login: "파트너사 포털 로그인",
  partner_logout: "파트너사 포털 로그아웃",
  partner_initial_setup: "파트너사 포털 초기 설정",
  partner_password_reset: "파트너사 포털 비밀번호 재설정",
  partner_password_change: "파트너사 포털 비밀번호 변경",
} as const satisfies Readonly<Record<AuthSecurityEventName, string>>;
