export const PRODUCT_EVENT_NAMES = [
  'page_view',
  'partner_detail_view',
  'partner_card_click',
  'category_filter_change',
  'directory_view_change',
  'search_execute',
  'sort_change',
  'partner_map_click',
  'reservation_click',
  'inquiry_click',
  'share_link_copy',
  'push_settings_view',
  'push_subscribe',
  'push_unsubscribe_device',
  'push_unsubscribe_all',
  'push_preference_change',
  'suggest_submit',
  'partner_registration_submit',
  'partner_registration_xlsx_submit',
  'partner_portal_brand_registration_submit',
  'pwa_install_click',
  'certification_view',
  'certification_qr_open',
  'certification_qr_verify',
  'partner_review_create',
  'partner_review_update',
  'partner_review_delete',
  'partner_review_recommend',
  'partner_review_disrecommend',
  'home_banner_click',
  'coupon_view',
  'coupon_copy',
  'coupon_redeem',
  'ad_push_send',
] as const;

export type ProductEventName = (typeof PRODUCT_EVENT_NAMES)[number];

export const ADMIN_AUDIT_ACTIONS = [
  'login',
  'logout',
  'category_create',
  'category_update',
  'category_delete',
  'partner_company_create',
  'partner_company_update',
  'partner_company_delete',
  'partner_create',
  'partner_update',
  'partner_delete',
  'partner_change_request_approve',
  'partner_change_request_reject',
  'member_update',
  'member_directory_sync',
  'member_sync',
  'member_mattermost_login_disable_generation',
  'member_email_login_transition',
  'member_manual_add',
  'member_manual_setup_link_reissue',
  'member_direct_create',
  'member_delete',
  'cycle_settings_update',
  'cycle_settings_early_start',
  'cycle_settings_restore',
  'cohort_card_theme_upsert',
  'cohort_card_theme_delete',
  'push_send',
  'push_log_delete',
  'partner_account_update',
  'partner_account_create',
  'partner_account_company_update',
  'partner_account_initial_setup_link_generate',
  'partner_account_initial_setup_link_send',
  'partner_review_hide',
  'partner_review_restore',
  'partner_review_update',
  'partner_review_delete',
  'partner_portal_immediate_update',
  'partner_portal_change_request_submit',
  'partner_portal_change_request_cancel',
  'partner_portal_review_hide',
  'partner_portal_review_restore',
  'promotion_event_create',
  'promotion_event_update',
  'promotion_event_delete',
  'promotion_slide_create',
  'promotion_slide_update',
  'promotion_slide_delete',
  'promotion_slide_bulk_update',
  'event_reward_draw_preview',
  'event_reward_draw_create',
  'event_reward_winner_notification_test_send',
  'event_reward_winner_notification_send',
  'ad_campaign_create',
  'ad_campaign_status_update',
  'ad_coupon_create',
  'partner_brand_plan_update',
  'partner_company_plan_update',
  'partner_plan_bank_transfer_confirmed',
  'partner_plan_upgrade_approved',
  'partner_plan_upgrade_rejected',
  'admin_account_create',
  'admin_account_setup_link_issue',
  'admin_account_status_update',
  'admin_account_permissions_update',
  'admin_account_template_apply',
  'graduate_verification_review_start',
  'graduate_verification_approve',
  'graduate_verification_setup_email_resend',
  'graduate_verification_reject',
  'graduate_verification_resubmission_request',
  'member_profile_photo_approve',
  'member_profile_photo_reject',
  'member_profile_photo_active_reject',
  'member_profile_photo_replace',
  'graduate_certificate_view',
  'graduate_profile_photo_view',
  'member_profile_photo_view',
  'admin_log_export_requested',
] as const;

export type AdminAuditAction = (typeof ADMIN_AUDIT_ACTIONS)[number];

export const AUTH_SECURITY_EVENT_NAMES = [
  'member_login',
  'member_logout',
  'member_signup_complete',
  'member_ssafy_verify',
  'member_email_verification',
  'ssafy_verify_api_trace',
  'member_policy_consent',
  'member_password_reset_ssafy',
  'member_password_reset_complete',
  'member_password_reset',
  'member_password_change',
  'member_delete',
  'graduate_email_verification',
  'graduate_verification_submit',
  'graduate_password_setup',
  'graduate_password_reset',
  'admin_login',
  'admin_access',
  'partner_login',
  'partner_logout',
  'partner_initial_setup',
  'partner_password_reset',
  'partner_password_change',
] as const;

export type AuthSecurityEventName = (typeof AUTH_SECURITY_EVENT_NAMES)[number];
export type AuthSecurityStatus = 'success' | 'failure' | 'blocked';
export type EventActorType = 'guest' | 'member' | 'admin' | 'partner' | 'system';

const PRODUCT_EVENT_NAME_SET = new Set<string>(PRODUCT_EVENT_NAMES);

export function isProductEventName(value: string): value is ProductEventName {
  return PRODUCT_EVENT_NAME_SET.has(value);
}
