export const partnerFormErrorMessages: Record<string, string> = {
  partner_form_missing_required: "업체명, 카테고리, 위치를 입력해 주세요.",
  partner_form_missing_name: "업체명을 입력해 주세요.",
  partner_form_missing_category: "카테고리를 선택해 주세요.",
  partner_form_missing_location: "위치를 입력해 주세요.",
  partner_form_invalid_campus_slugs: "노출 캠퍼스를 하나 이상 선택해 주세요.",
  partner_form_invalid_period: "기간 입력을 확인해 주세요.",
  partner_form_invalid_map_url: "지도 링크는 올바른 http(s) 주소여야 합니다.",
  partner_form_invalid_benefit_action_type: "혜택 이용 방식은 인증, 외부 링크, 현장 이용, 없음 중 하나여야 합니다.",
  partner_form_invalid_benefit_action_link: "혜택 이용 링크 형식을 확인해 주세요.",
  partner_form_invalid_reservation_url: "혜택 이용 링크 형식을 확인해 주세요.",
  partner_form_invalid_inquiry_url: "문의 링크 형식을 확인해 주세요.",
  partner_form_invalid_visibility: "노출 상태는 공개, 대외비, 비공개 중 하나여야 합니다.",
  partner_form_invalid_applies_to: "적용 대상을 하나 이상 선택해 주세요.",
  partner_form_invalid_request: "입력값을 확인해 주세요.",
  partner_company_missing_name: "협력사명을 입력해 주세요.",
  partner_company_missing_email: "담당자 이메일을 입력해 주세요.",
  partner_company_invalid_email: "담당자 이메일 형식이 올바르지 않습니다.",
  partner_company_invalid_request: "협력사 입력값을 확인해 주세요.",
};
