import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { chmod, mkdtemp, mkdir, readFile, realpath, stat, symlink, writeFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { exportRecoveryIdentity, importRecoveryIdentity } from "../scripts/self-host-operations/export-recovery-identity.mjs";

// Public, disposable test material generated by age-keygen 1.3.1. Never use for a backup.
const SYNTHETIC_IDENTITY = "AGE-SECRET-KEY-13RRJV3VWDHC234FE3R9ECG4AQ6XWT3DWCZCEWPLXFR6ES4KMK2KQ6TCSAM";

test("escrow exports only to a private external file, preserves keys off output and refuses overwrite", async () => {
  const temp = await realpath(await mkdtemp(join(tmpdir(), "escrow-contract-")));
  try {
    const root = join(temp, "repo"); await mkdir(root, { mode: 0o700 });
    const source = join(temp, "identity"); const destination = join(temp, "escrow.json");
    const fixture = SYNTHETIC_IDENTITY;
    await writeFile(source, fixture, { mode: 0o600 });
    assert.deepEqual(await exportRecoveryIdentity({ source, destination, root }), { exported: true, version: 1 });
    assert.equal(JSON.parse(await readFile(destination, "utf8")).identity, fixture);
    assert.equal((await stat(destination)).mode & 0o777, 0o600);
    await assert.rejects(exportRecoveryIdentity({ source, destination, root }));
    await assert.rejects(exportRecoveryIdentity({ source, destination: join(root, "bad.json"), root }), /ESCROW_PRIVATE_PATH_REQUIRED/);
  } finally { await rm(temp, { recursive: true, force: true }); }
});

test("escrow rejects truncated, corrupted and unsupported identity text before creating an output", async () => {
  const temp = await realpath(await mkdtemp(join(tmpdir(), "escrow-invalid-")));
  try {
    const root = join(temp, "repo"); await mkdir(root, { mode: 0o700 });
    for (const [index, identity] of [
      `AGE-SECRET-KEY-${"A".repeat(58)}`,
      SYNTHETIC_IDENTITY.slice(0, -1),
      `${SYNTHETIC_IDENTITY.slice(0, -1)}${SYNTHETIC_IDENTITY.endsWith("Q") ? "P" : "Q"}`,
      SYNTHETIC_IDENTITY.toLowerCase(),
      `${SYNTHETIC_IDENTITY}\n${SYNTHETIC_IDENTITY}`,
    ].entries()) {
      const source = join(temp, `identity-${index}`);
      const destination = join(temp, `escrow-${index}.json`);
      await writeFile(source, identity, { mode: 0o600 });
      await assert.rejects(exportRecoveryIdentity({ source, destination, root }), /ESCROW_IDENTITY_FORMAT_INVALID/);
      await assert.rejects(stat(destination), { code: "ENOENT" });
    }
  } finally { await rm(temp, { recursive: true, force: true }); }
});

test("escrow imports its versioned envelope as a private age identity without overwriting", async () => {
  const temp = await realpath(await mkdtemp(join(tmpdir(), "escrow-import-")));
  try {
    const root = join(temp, "repo"); await mkdir(root, { mode: 0o700 });
    const source = join(temp, "identity"); const envelope = join(temp, "escrow.json");
    const destination = join(temp, "restored-identity");
    await writeFile(source, `# synthetic test fixture\r\n${SYNTHETIC_IDENTITY}\r\n`, { mode: 0o600 });
    await exportRecoveryIdentity({ source, destination: envelope, root });
    assert.deepEqual(await importRecoveryIdentity({ source: envelope, destination, root }), { imported: true, version: 1 });
    assert.equal(await readFile(destination, "utf8"), `${SYNTHETIC_IDENTITY}\n`);
    assert.equal((await stat(destination)).mode & 0o777, 0o600);
    await assert.rejects(importRecoveryIdentity({ source: envelope, destination, root }), { code: "EEXIST" });
    const valid = JSON.parse(await readFile(envelope, "utf8"));
    for (const [index, contents] of [
      "{", JSON.stringify({ ...valid, version: 2 }),
      JSON.stringify({ ...valid, kind: "unrecognized" }),
      JSON.stringify({ ...valid, exportedAt: "invalid" }),
      JSON.stringify({ ...valid, identity: SYNTHETIC_IDENTITY.slice(0, -1) }),
      JSON.stringify({ ...valid, unexpected: "field" }),
    ].entries()) {
      const malformed = join(temp, `malformed-${index}`);
      const output = join(temp, `output-${index}`);
      await writeFile(malformed, contents, { mode: 0o600 });
      await assert.rejects(importRecoveryIdentity({ source: malformed, destination: output, root }), /ESCROW_(?:ENVELOPE|IDENTITY)_FORMAT_INVALID/);
      await assert.rejects(stat(output), { code: "ENOENT" });
    }
  } finally { await rm(temp, { recursive: true, force: true }); }
});

test("both directions reject public, repository and symbolic-link paths", async () => {
  const temp = await realpath(await mkdtemp(join(tmpdir(), "escrow-paths-")));
  try {
    const root = join(temp, "repo"); await mkdir(root, { mode: 0o700 });
    for (const [index, operation] of [exportRecoveryIdentity, importRecoveryIdentity].entries()) {
      const source = join(temp, `source-${index}`);
      const destination = join(temp, `destination-${index}`);
      const text = index === 0 ? SYNTHETIC_IDENTITY : JSON.stringify({ version: 1, kind: "age-recovery-identity", exportedAt: "2026-10-06T00:00:00.000Z", identity: SYNTHETIC_IDENTITY });
      await writeFile(source, text, { mode: 0o644 });
      await assert.rejects(operation({ source, destination, root }), /ESCROW_PRIVATE_PATH_REQUIRED/);
      await chmod(source, 0o600);
      const sourceLink = join(temp, `source-link-${index}`); await symlink(source, sourceLink);
      await assert.rejects(operation({ source: sourceLink, destination, root }), /ESCROW_PRIVATE_PATH_REQUIRED/);
      await assert.rejects(operation({ source, destination: join(root, `output-${index}`), root }), /ESCROW_PRIVATE_PATH_REQUIRED/);
      const privateParent = join(temp, `private-${index}`); await mkdir(privateParent, { mode: 0o700 });
      const parentLink = join(temp, `parent-link-${index}`); await symlink(privateParent, parentLink);
      await assert.rejects(operation({ source, destination: join(parentLink, "output"), root }), /ESCROW_PRIVATE_PATH_REQUIRED/);
      await chmod(privateParent, 0o755);
      await assert.rejects(operation({ source, destination: join(privateParent, "output"), root }), /ESCROW_PRIVATE_PATH_REQUIRED/);
      await stat(source);
      await assert.rejects(stat(destination), { code: "ENOENT" });
    }
  } finally { await rm(temp, { recursive: true, force: true }); }
});

for (const invocation of ["canonical", "control/current", "file-alias"] as const) {
test(`the ${invocation} CLI executes both operations and fails closed without exposing private contents`, async () => {
  const temp = await realpath(await mkdtemp(join(tmpdir(), "escrow-cli-")));
  try {
    const source = join(temp, "identity"); const envelope = join(temp, "escrow.json");
    const restored = join(temp, "restored");
    const canonicalScript = fileURLToPath(new URL("../scripts/self-host-operations/export-recovery-identity.mjs", import.meta.url));
    let script = canonicalScript;
    if (invocation === "control/current") {
      const control = join(temp, "control"); await mkdir(control, { mode: 0o700 });
      const current = join(control, "current");
      await symlink(dirname(dirname(dirname(canonicalScript))), current, "dir");
      script = join(current, "scripts/self-host-operations/export-recovery-identity.mjs");
    } else if (invocation === "file-alias") {
      script = join(temp, "identity #entry%.mjs");
      await symlink(canonicalScript, script, "file");
    }
    await writeFile(source, SYNTHETIC_IDENTITY, { mode: 0o600 });
    for (const [args, receipt] of [
      [[source, envelope], { exported: true, version: 1 }],
      [["--import", envelope, restored], { imported: true, version: 1 }],
    ] as const) {
      const result = spawnSync(process.execPath, [script, ...args], { encoding: "utf8" });
      assert.equal(result.status, 0);
      assert.deepEqual(JSON.parse(result.stdout), receipt);
      assert.equal(result.stderr, "");
    }
    const exported = await readFile(envelope, "utf8");
    assert.equal(JSON.parse(exported).identity, SYNTHETIC_IDENTITY);
    assert.equal(await readFile(restored, "utf8"), `${SYNTHETIC_IDENTITY}\n`);
    assert.equal((await stat(envelope)).mode & 0o777, 0o600);
    assert.equal((await stat(restored)).mode & 0o777, 0o600);
    for (const args of [[], [source], ["--import"], ["--import", envelope], [source, envelope], ["--import", envelope, restored], [source, envelope, "extra"], ["--import", envelope, restored, "extra"]]) {
      const result = spawnSync(process.execPath, [script, ...args], { encoding: "utf8" });
      assert.equal(result.status, 1);
      assert.equal(result.stdout, "");
      assert.equal(result.stderr, "ESCROW_EXPORT_FAILED\n");
    }
    assert.equal(await readFile(envelope, "utf8"), exported);
    assert.equal(await readFile(restored, "utf8"), `${SYNTHETIC_IDENTITY}\n`);
  } finally { await rm(temp, { recursive: true, force: true }); }
});
}

test("importing the escrow module from eval or stdin never executes its CLI", () => {
  const script = new URL("../scripts/self-host-operations/export-recovery-identity.mjs", import.meta.url).href;
  const input = `const module = await import(${JSON.stringify(script)}); if (typeof module.exportRecoveryIdentity !== "function" || typeof module.importRecoveryIdentity !== "function") process.exitCode = 2;`;
  for (const args of [["--input-type=module", "--eval", input], ["--input-type=module", "-"]]) {
    const result = spawnSync(process.execPath, args, { encoding: "utf8", input });
    assert.equal(result.status, 0);
    assert.equal(result.stdout, "");
    assert.equal(result.stderr, "");
  }
});

import { buildRestoreTiming } from "../scripts/self-host-operations/restore-production-backup.mjs";
test("restore timing distinguishes key provenance and rejects impossible durations", () => {
  assert.deepEqual(buildRestoreTiming("2026-10-05T00:00:00Z", "2026-10-05T00:02:30Z", "offline-escrow"), { startedAt: "2026-10-05T00:00:00Z", finishedAt: "2026-10-05T00:02:30Z", durationSeconds: 150, identitySource: "offline-escrow" });
  assert.throws(() => buildRestoreTiming("invalid", "invalid"), /RESTORE_TIMING_INVALID/);
  assert.throws(() => buildRestoreTiming("2026-10-05T00:02:30Z", "2026-10-05T00:00:00Z"), /RESTORE_TIMING_INVALID/);
});
